version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - exsilium
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: moment
    versions:
    - 2.29.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: xmldom
    versions:
    - 0.4.0
  - dependency-name: lodash
    versions:
    - 4.17.20
